try repro

diff --git a/eng/pipelines/templates/Tests_On_Mac.yml b/eng/pipelines/templates/Tests_On_Mac.yml
--- a/eng/pipelines/templates/Tests_On_Mac.yml
+++ b/eng/pipelines/templates/Tests_On_Mac.yml
@@ -1,39 +1,53 @@
 steps:
-- task: ShellScript@2
-  displayName: "Run Tests (stop on error)"
-  continueOnError: "false"
-  inputs:
-    scriptPath: "scripts/funcTests/runFuncTests2.sh"
-    args: '6.0.3xx'
-    disableAutoCwd: "true"
-    cwd: "$(Build.Repository.LocalPath)"
-  condition: "and(succeeded(), not(eq(variables['IsOfficialBuild'], 'true')))"
-
 - script: |
     cd $BUILD_REPOSITORY_LOCALPATH
-    export VSTEST_BUILD_TRACE=1
-    echo "VSTEST_BUILD_TRACE : $VSTEST_BUILD_TRACE"
-    echo "./cli/dotnet test ./test/NuGet.Core.Tests/NuGet.Common.Test/bin/release/netcoreapp3.1/NuGet.Common.Test.dll --blame-crash --blame-crash-dump-type diag"
-    ./cli/dotnet test ./test/NuGet.Core.Tests/NuGet.Common.Test/bin/release/netcoreapp3.1/NuGet.Common.Test.dll --blame-crash --blame-crash-dump-type diag
-    echo "single test exitcode is $?"
+    # Download the CLI install script to cli
+    echo "Installing dotnet CLI"
+    mkdir -p cli
+    curl -o cli/dotnet-install.sh -L https://dot.net/v1/dotnet-install.sh
 
-    cd ~/Library/Logs/DiagnosticReports
-    pwd
-    echo "==== ls ====="
-    ls -l
+    # Run install.sh
+    chmod +x cli/dotnet-install.sh
+
+    # Get recommended version for bootstrapping testing version
+    # Install .NET 3.1 runtime
+    echo "cli/dotnet-install.sh --install-dir cli --runtime dotnet --channel 3.1 -nopath"
+    cli/dotnet-install.sh --install-dir cli --runtime dotnet --channel 3.1 -nopath
+
+    # Install .NET 3.1 runtime
+    echo "cli/dotnet-install.sh --install-dir cli --runtime dotnet --channel 5.0 -nopath"
+    cli/dotnet-install.sh --install-dir cli --runtime dotnet --channel 5.0 -nopath
+
+    if (( $? )); then
+	     echo "The .NET CLI Install failed!!"
+	     exit 1
+    fi
+
+    # Disable .NET CLI Install Lookup
+    DOTNET_MULTILEVEL_LOOKUP=0
+
+    DOTNET="$(pwd)/cli/dotnet"
+
+    echo "cli/dotnet-install.sh --install-dir cli --channel 6.0.4xx --quality signed -nopath"
+    cli/dotnet-install.sh --install-dir cli --channel 6.0.4xx --quality signed -nopath
+
+    # Let the dotnet cli expand and decompress first if it's a first-run
+    $DOTNET --info
+
     cd $BUILD_REPOSITORY_LOCALPATH
-    mkdir log
-    cp ~/Library/Logs/DiagnosticReports/*  ./log/*
-    echo "==== ls -l $BUILD_REPOSITORY_LOCALPATH/log ====="
-    ls -l $BUILD_REPOSITORY_LOCALPATH/log
+    echo "$DOTNET build ./test/NuGet.Core.Tests/NuGet.Resolver.Test/NuGet.Resolver.Test.csproj"
+    $DOTNET build ./test/NuGet.Core.Tests/NuGet.Resolver.Test/NuGet.Resolver.Test.csproj
 
-- task: PublishBuildArtifacts@1
-  displayName: "Publish log"
-  inputs:
-    PathtoPublish: "$(Build.Repository.LocalPath)/log"
-    ArtifactName: "$(Agent.JobName)"
-    ArtifactType: "Container"
-  condition: "succeededOrFailed()"
+    echo "$DOTNET test ./test/NuGet.Core.Tests/NuGet.Resolver.Test/bin/Debug/netcoreapp3.1/NuGet.Resolver.Test.dll"
+    $DOTNET test ./test/NuGet.Core.Tests/NuGet.Resolver.Test/bin/Debug/netcoreapp3.1/NuGet.Resolver.Test.dll
+
+# - task: PublishBuildArtifacts@1
+#   displayName: "Publish log"
+#   inputs:
+#     PathtoPublish: "$(Build.Repository.LocalPath)/log"
+#     ArtifactName: "$(Agent.JobName)"
+#     ArtifactType: "Container"
+#   condition: "succeededOrFailed()"
 
 - task: PublishTestResults@2
   displayName: "Publish Test Results"
